### ISSUE TITLE
NVIDIADeepStreamSDK IoT Image Is Broken

### ISSUE THREAD

**Issue by mitchross** [Azure-Samples/NVIDIA-Deepstream-Azure-IoT-Edge-on-a-NVIDIA-Jetson-Nano#7] opened 2019-12-24 18:49 UTC
Container fails to run (gst-plugin-scanner:6): GStreamer-WARNING **: 18:47:09.647: Failed to load plugin '/usr/lib/aarch64-linux-gnu/gstreamer-1.0/deepstream/libnvdsgst_infer.so': libnvparsers.so.5: cannot open shared object file: No such file or directory

**Comment by ebertrams** [comment] 2019-12-26 22:32
There are 2 SKUs of NVIDIA DeepStream in Azure Marketplace: one for x86 architectures (aarch64) and one for arm64 architectures. If you have a Jetson Nano, did you select the ARM64 one, also called the Jetson one by NVIDIA? Thanks

**Comment by jwf5426** [comment] 2019-12-26 23:21
Hey there,

I have been having the same issue for the last couple of days. I tried using both the latest **Jetson Nano Developer Kit SD Card Image (w/ JP 4.3 & Release Date 2019/12/17)** and using the SDK Manager to install JetPack 4.3 + Deepstream. Additionally, I confirmed that I using the ARM64 Nvidia Deepstream SDK Azure marketplace module.  None of these steps resolved the error.

I can confirm from my testing that using **Jetson Nano Developer Kit SD Card Image w/ JP 4.2.3 & Release Date 2019/11/19** resolves this error.

I am not sure what the difference is between these two versions. This issue will most likely need to be resolved by Nvidia since the latest SD Card Image does not work with the latest ARM64 Nvidia Deepstream SDK Azure marketplace module.

For now, I recommend using the older SD Card Image until this issue is resolved by Nvidia. You can download it at the [Jetson Download Center](https://developer.nvidia.com/embedded/downloads).

Good luck.

**Comment by mitchross** [comment] 2019-12-27 00:19
Some discussion. https://devtalk.nvidia.com/default/topic/1068898/nvidiadeepstreamsdk-iot-image-is-broken-/?offset=5#5414903

**Comment by ebertrams** [comment] 2020-01-15 17:59
Are you using Jetpack version 4.2 or the new version 4.3? The current Deepstream image in the marketplace (4.0.1) only works with Jetpack 4.2. I just updated the instructions. NVIDIA is working on publishing a new Deepstream image (4.0.2) in the Azure Marketplace that works with Jetpack 4.3. If you need DeepStream 4.0.2 quickly, you can get it from NVIDIA NGC (Deepstream container named deepstream-l4t, tag 4.0.2-19.12-iot). I ll close this issue once the new version is published and instructions updated accordingly. Thanks

**Comment by ebertrams** [comment] 2020-01-18 00:51
@mitchross Hopefully this will be completed in a week or two. NVIDIA is actively working on it. In the meantime, you can use the container in NVIDIA NGC.

**Comment by mitchross** [comment] 2020-01-26 17:34
any update?

**Comment by ebertrams** [comment] 2020-01-28 01:15
@mitchross submission has been submitted by NVIDIA and certification is currently in progress. This repo should be updated by the end of this week.

**Comment by mitchross** [comment] 2020-02-01 16:29
Looks like the update is out, can you update this repo? https://azuremarketplace.microsoft.com/en-us/marketplace/apps/nvidia.deepstream-iot?tab=Overview

**Comment by ebertrams** [comment] 2020-02-05 18:29
@mitchross updated! Closing this issue

**Closed by ebertrams** 2020-02-05 18:29 UTC

**Comment by psyllost** [comment] 2020-12-07 20:40
Does DeepStream image 4.0.2 work with JetPack version 4.4? I ran into the same error.
